---

language: python
python:
  - '3.8'
  - '3.7'
os: linux
services:
  - docker
cache:
  pip: true
  directories:
  - ".tox"
install:
  - pip install tox-travis
env:
  jobs:
    - TOX_DISTRO=debian10-jdk8          TOX_ANSIBLE={29,28,27}
    - TOX_DISTRO=debian10-jdk11         TOX_ANSIBLE={29,28,27}
    - TOX_DISTRO=debian9-jdk8           TOX_ANSIBLE={29,28,27}
    - TOX_DISTRO=debian9-jdk11          TOX_ANSIBLE={29,28,27}
    - TOX_DISTRO=ubuntu2004-jdk11       TOX_ANSIBLE={29,28,27}
    - TOX_DISTRO=ubuntu2004-jdk14       TOX_ANSIBLE={29,28,27}
script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-ansible${TOX_ANSIBLE}-${TOX_DISTRO}
  - |
    rm -r .tox/py*/log/*
    find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
  
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
